name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      allure:
        image: frankescobar/allure-docker-service:latest
        ports:
          - "4040:4040"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --browser=chrome

    - name: Generate Allure Report
      run: |
        allure generate reports/allure-results --clean -o reports/allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: reports/allure-report
